/*
 * The original project was written in C++ and later decompiled back to C.  As a
 * consequence a number of compiler specific constructs (such as direct access
 * to `__stack_chk_guard`) were emitted, which causes problems when compiling
 * the file as a freestanding C translation unit.  GCC in particular fails to
 * build the file because of missing type definitions and prototypes.  This
 * implementation provides the minimal declarations required for a clean
 * compilation while preserving the behaviour of the original code.
 */

#include <stdint.h>

/*
 * When GCC emits stack protector code it references the variables below.  They
 * are normally supplied by the C runtime, but when compiling this file in
 * isolation we need to declare them ourselves.  They are defined by the
 * runtime, so we only provide extern declarations here.
 */
extern void *__stack_chk_guard;
void __stack_chk_fail(void);

/* Prototypes for helper functions provided by the surrounding library. */
extern int64_t IOTC_Session_Read_Check_Lost_Data_And_Datatype(
    int64_t sid, void *buf, int64_t size, int64_t timeout,
    unsigned char *lost, unsigned char *datatype, int32_t flags,
    int32_t unused);

extern int32_t *tutk_third_BIO_get_data(void *bio);
extern void *tutk_third_SSL_get_rbio(int64_t ssl);
extern int32_t tutk_third_SSL_shutdown(int64_t ssl);
extern int32_t tutk_third_SSL_get_error(int64_t ssl, int32_t ret);
extern void TUTK_LOG_MSG(int level, const char *module, int type,
                         const char *fmt, const char *func,
                         int32_t sid, int32_t chID, int32_t ret);
extern int64_t translate_Error(int32_t ret, int64_t ssl);

int64_t IOTC_Session_Read(int64_t sid, void *buf, int64_t size,
                          int64_t timeout, int32_t flags)
{
    unsigned char lost = 0;
    unsigned char datatype = 0;
    /*
     * Capture the current stack guard value and compare it after the call in
     * order to emulate the behaviour generated by GCC's stack protector.
     */
    void *guard = __stack_chk_guard;
    int64_t ret = IOTC_Session_Read_Check_Lost_Data_And_Datatype(
        sid, buf, size, timeout, &lost, &datatype, flags, 0);

    if (ret == 0 && guard == __stack_chk_guard)
        return ret;

    /* Guard value changed – trigger the failure handler. */
    __stack_chk_fail();
    /* no return */
}

int64_t IOTC_sCHL_shutdown(int64_t ssl)
{
    int32_t *bio = tutk_third_BIO_get_data(tutk_third_SSL_get_rbio(ssl));
    int32_t ret;

    if (!bio[21])
    {
        ret = 0;
        bio[20] = 1;            /* mark shutdown requested */
    }
    else
    {
        int32_t tmp = tutk_third_SSL_shutdown(ssl);
        bio[22] = 1;            /* shutdown completed */
        ret = (tmp <= 0) ? tutk_third_SSL_get_error(ssl, tmp) : 0;
    }

    TUTK_LOG_MSG(0, "SCHL", 2,
                 "[%s] SID[%d] ChID[%d] ret[%d]",
                 "IOTC_sCHL_shutdown", bio[0], bio[1], ret);
    return translate_Error(ret, ssl);
}

/*
 * Data endianness helpers.  The original shared library exposes two utility
 * functions that convert 32-bit integers between host and network byte order.
 * Reimplement them here using purely standard C so that unit tests do not
 * depend on platform specific headers such as <arpa/inet.h>.
 */

static inline uint32_t bswap32(uint32_t v)
{
    return ((v & 0x000000FFu) << 24) |
           ((v & 0x0000FF00u) << 8)  |
           ((v & 0x00FF0000u) >> 8)  |
           ((v & 0xFF000000u) >> 24);
}

uint32_t IOTC_Data_ntoh(uint32_t data)
{
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
    return bswap32(data);
#else
    return data;
#endif
}

uint32_t IOTC_Data_hton(uint32_t data)
{
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
    return bswap32(data);
#else
    return data;
#endif
}

