/*
 * The original project was written in C++ and later decompiled back to C.  As a
 * consequence a number of compiler specific constructs (such as direct access
 * to `__stack_chk_guard`) were emitted, which causes problems when compiling
 * the file as a freestanding C translation unit.  GCC in particular fails to
 * build the file because of missing type definitions and prototypes.  This
 * implementation provides the minimal declarations required for a clean
 * compilation while preserving the behaviour of the original code.
 */

#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include "libIOTCAPIsT.h"

/*
 * When GCC emits stack protector code it references the variables below.  They
 * are normally supplied by the C runtime, but when compiling this file in
 * isolation we need to declare them ourselves.  They are defined by the
 * runtime, so we only provide extern declarations here.
 */
extern void *__stack_chk_guard;
void __stack_chk_fail(void);

/* Prototypes for helper functions provided by the surrounding library. */
extern int64_t IOTC_Session_Read_Check_Lost_Data_And_Datatype(
    int64_t sid, void *buf, int64_t size, int64_t timeout,
    unsigned char *lost, unsigned char *datatype, int32_t flags,
    int32_t unused);

extern int32_t *tutk_third_BIO_get_data(void *bio);
extern void *tutk_third_SSL_get_rbio(int64_t ssl);
extern int32_t tutk_third_SSL_shutdown(int64_t ssl);
extern int32_t tutk_third_SSL_get_error(int64_t ssl, int32_t ret);
extern void TUTK_LOG_MSG(int level, const char *module, int type,
                         const char *fmt, const char *func,
                         int32_t sid, int32_t chID, int32_t ret);
extern int64_t translate_Error(int32_t ret, int64_t ssl);

int64_t IOTC_Session_Read(int64_t sid, void *buf, int64_t size,
                          int64_t timeout, int32_t flags)
{
    unsigned char lost = 0;
    unsigned char datatype = 0;
    /*
     * Capture the current stack guard value and compare it after the call in
     * order to emulate the behaviour generated by GCC's stack protector.
     */
    void *guard = __stack_chk_guard;
    int64_t ret = IOTC_Session_Read_Check_Lost_Data_And_Datatype(
        sid, buf, size, timeout, &lost, &datatype, flags, 0);

    if (ret == 0 && guard == __stack_chk_guard)
        return ret;

    /* Guard value changed – trigger the failure handler. */
    __stack_chk_fail();
    /* no return */
#if defined(__GNUC__)
    __builtin_unreachable();
#endif
}

int64_t IOTC_sCHL_shutdown(int64_t ssl)
{
    int32_t *bio = tutk_third_BIO_get_data(tutk_third_SSL_get_rbio(ssl));
    int32_t ret;

    if (!bio[21])
    {
        ret = 0;
        bio[20] = 1;            /* mark shutdown requested */
    }
    else
    {
        int32_t tmp = tutk_third_SSL_shutdown(ssl);
        bio[22] = 1;            /* shutdown completed */
        ret = (tmp <= 0) ? tutk_third_SSL_get_error(ssl, tmp) : 0;
    }

    TUTK_LOG_MSG(0, "SCHL", 2,
                 "[%s] SID[%d] ChID[%d] ret[%d]",
                 "IOTC_sCHL_shutdown", bio[0], bio[1], ret);
    return translate_Error(ret, ssl);
}

/*
 * Data endianness helpers.  The original shared library exposes two utility
 * functions that convert 32-bit integers between host and network byte order.
 * Reimplement them here using purely standard C so that unit tests do not
 * depend on platform specific headers such as <arpa/inet.h>.
 */

static inline uint32_t bswap32(uint32_t v)
{
    return ((v & 0x000000FFu) << 24) |
           ((v & 0x0000FF00u) << 8)  |
           ((v & 0x00FF0000u) >> 8)  |
           ((v & 0xFF000000u) >> 24);
}

uint32_t IOTC_Data_ntoh(uint32_t data)
{
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
    return bswap32(data);
#else
    return data;
#endif
}

uint32_t IOTC_Data_hton(uint32_t data)
{
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
    return bswap32(data);
#else
    return data;
#endif
}

/*
 * Convert the fields of an IOTC header structure between host and
 * network byte order.  The exact semantics of the fields are not
 * important here; the helper simply swaps each 32-bit value.
 */

void IOTC_Header_ntoh(IOTCHeader *hdr)
{
    hdr->flag      = IOTC_Data_ntoh(hdr->flag);
    hdr->sid       = IOTC_Data_ntoh(hdr->sid);
    hdr->seq       = IOTC_Data_ntoh(hdr->seq);
    hdr->timestamp = IOTC_Data_ntoh(hdr->timestamp);
    hdr->payload   = IOTC_Data_ntoh(hdr->payload);
}

void IOTC_Header_hton(IOTCHeader *hdr)
{
    hdr->flag      = IOTC_Data_hton(hdr->flag);
    hdr->sid       = IOTC_Data_hton(hdr->sid);
    hdr->seq       = IOTC_Data_hton(hdr->seq);
    hdr->timestamp = IOTC_Data_hton(hdr->timestamp);
    hdr->payload   = IOTC_Data_hton(hdr->payload);
}

/*
 * Retrieve the version of the IOTC library.  The shared object exposes
 * a function that writes a 32-bit packed version number into the caller's
 * provided pointer.  Reverse engineering shows the value 0x010d0700 which
 * corresponds to version 1.13.7.0.
 */
void IOTC_Get_Version(uint32_t *pnVersion)
{
    if (pnVersion)
        *pnVersion = 0x010d0700u;
}

/* Return the version string matching IOTC_Get_Version. */
const char *IOTC_Get_Version_String(void)
{
    return "1.13.7.0";
}

/* ------------------------------------------------------------------------- */
/* Session channel management                                                 */

/*
 * The original library exposes helpers that toggle logical channels within a
 * session.  The real implementation likely interacts with the networking
 * stack but for testing purposes a very small in-memory model suffices.  Each
 * session can enable up to 32 channels which we track using a bit mask.
 */

typedef struct {
    int64_t sid;         /* session identifier */
    uint32_t chan_mask;  /* bit mask of enabled channels */
} SessionEntry;

/*
 * The real library allows the maximum number of concurrent sessions to be
 * configured via IOTC_Set_Max_Session_Number.  To emulate this behaviour the
 * test implementation allocates the session table dynamically and resizes it
 * on demand.
 */
static SessionEntry *session_table;      /* dynamically sized array */
static unsigned int max_sessions = 8;    /* default capacity */

/* Ensure the session table has been allocated before use. */
static void ensure_session_table(void)
{
    if (!session_table)
        session_table = calloc(max_sessions, sizeof(SessionEntry));
}

/* Locate the table entry for a session, optionally creating a new one. */
static SessionEntry *find_session(int64_t sid, int create)
{
    ensure_session_table();

    for (size_t i = 0; i < max_sessions; ++i)
        if (session_table[i].sid == sid)
            return &session_table[i];

    if (!create)
        return NULL;

    for (size_t i = 0; i < max_sessions; ++i)
        if (session_table[i].sid == 0)
        {
            session_table[i].sid = sid;
            session_table[i].chan_mask = 0;
            return &session_table[i];
        }

    return NULL; /* no space left */
}

/* --------------------------------------------------------------------- */
/* Session allocation helpers                                            */

/* Obtain a tutk_platform_free session identifier.  The simple model uses an
 * incrementing counter and reserves a slot in the session table for the
 * caller.  When the table is full -1 is returned. */
int64_t IOTC_Get_SessionID(void)
{
    static int64_t next_sid = 1;

    ensure_session_table();

    for (unsigned int attempt = 0; attempt < max_sessions; ++attempt)
    {
        int64_t sid = next_sid++;
        if (next_sid <= 0)
            next_sid = 1;

        if (!find_session(sid, 0))
        {
            if (find_session(sid, 1))
                return sid;
        }
    }

    return -1; /* table full */
}

/* Set the maximum number of sessions tracked by the in-memory model.  Existing
 * session information is preserved up to the new limit. */
int64_t IOTC_Set_Max_Session_Number(unsigned int n)
{
    if (n == 0)
        return -1;

    SessionEntry *new_table = calloc(n, sizeof(SessionEntry));
    if (!new_table)
        return -1;

    if (session_table)
    {
        unsigned int copy = (n < max_sessions) ? n : max_sessions;
        for (unsigned int i = 0; i < copy; ++i)
            new_table[i] = session_table[i];
        free(session_table);
    }

    session_table = new_table;
    max_sessions = n;
    return (int64_t)n;
}

int64_t IOTC_Session_Channel_ON(int64_t sid, int32_t chID)
{
    if (chID < 0 || chID >= 32)
        return -1;

    SessionEntry *entry = find_session(sid, 1);
    if (!entry)
        return -1;

    entry->chan_mask |= (1u << chID);
    return 0;
}

int64_t IOTC_Session_Channel_OFF(int64_t sid, int32_t chID)
{
    if (chID < 0 || chID >= 32)
        return -1;

    SessionEntry *entry = find_session(sid, 0);
    if (!entry)
        return -1;

    entry->chan_mask &= ~(1u << chID);
    if (entry->chan_mask == 0)
        entry->sid = 0;

    return 0;
}

int64_t IOTC_Session_Channel_Check_ON_OFF(int64_t sid, int32_t chID)
{
    if (chID < 0 || chID >= 32)
        return 0;

    SessionEntry *entry = find_session(sid, 0);
    if (!entry)
        return 0;

    return (entry->chan_mask & (1u << chID)) ? 1 : 0;
}

int64_t IOTC_Session_Close(int64_t sid)
{
    SessionEntry *entry = find_session(sid, 0);
    if (!entry)
        return -1;
    entry->sid = 0;
    entry->chan_mask = 0;
    return 0;
}

int32_t IOTC_Session_Get_Free_Channel(int64_t sid)
{
    SessionEntry *entry = find_session(sid, 1);
    if (!entry)
        return -1;
    for (int32_t i = 0; i < 32; ++i)
        if (!(entry->chan_mask & (1u << i)))
            return i;
    return -1;
}

/* --------------------------------------------------------------------- */
/* Feature parity: IOTC_Listen, IOTC_Connect, IOTC_Session_Get_Info      */
/* These are stubs for compatibility with the .so, returning error codes */
/* or dummy values as appropriate.                                       */

int64_t IOTC_Listen(const char *uid, uint16_t port, uint32_t timeout_ms)
{
    (void)uid; (void)port; (void)timeout_ms;
    return -1; /* not implemented */
}

int64_t IOTC_Connect(const char *uid, const char *server, uint16_t port)
{
    (void)uid; (void)server; (void)port;
    return -1; /* not implemented */
}

int64_t IOTC_Session_Get_Info(int64_t sid, void *info)
{
    (void)sid; (void)info;
    return -1; /* not implemented */
}

/* --------------------------------------------------------------------- */
/* Feature parity: IOTC_Initialize, IOTC_DeInitialize                    */

int64_t IOTC_Initialize(void)
{
    /* No-op for test implementation */
    return 0;
}

int64_t IOTC_DeInitialize(void)
{
    /* Free session table if allocated */
    if (session_table) {
        free(session_table);
        session_table = NULL;
    }
    max_sessions = 8;
    return 0;
}

/* --------------------------------------------------------------------- */
/* Feature parity: IOTC_Get_Login_Info, IOTC_Get_Session_Status          */

int64_t IOTC_Get_Login_Info(int64_t sid, void *login_info)
{
    (void)sid; (void)login_info;
    return -1; /* not implemented */
}

int64_t IOTC_Get_Session_Status(int64_t sid)
{
    (void)sid;
    return -1; /* not implemented */
}

/* --------------------------------------------------------------------- */
/* Feature parity: IOTC_Session_Check                                    */

int64_t IOTC_Session_Check(int64_t sid)
{
    /* Return 1 if session exists, 0 otherwise */
    SessionEntry *entry = find_session(sid, 0);
    return entry ? 1 : 0;
}

/* --------------------------------------------------------------------- */
/* Feature parity: IOTC_Session_Get_Channel_ON_Count                     */

int32_t IOTC_Session_Get_Channel_ON_Count(int64_t sid)
{
    SessionEntry *entry = find_session(sid, 0);
    if (!entry)
        return 0;
    uint32_t mask = entry->chan_mask;
    int count = 0;
    for (int i = 0; i < 32; ++i)
        if (mask & (1u << i))
            ++count;
    return count;
}

/* --------------------------------------------------------------------- */
/* Feature parity: IOTC_Session_Get_My_SessionID                         */

int64_t IOTC_Session_Get_My_SessionID(void)
{
    /* Not meaningful in test context, return -1 */
    return -1;
}

/* --------------------------------------------------------------------- */
/* Feature parity: IOTC_Session_Get_Remote_Info                          */

int64_t IOTC_Session_Get_Remote_Info(int64_t sid, void *remote_info)
{
    (void)sid; (void)remote_info;
    return -1; /* not implemented */
}

/* --------------------------------------------------------------------- */
/* Feature parity: IOTC_Session_Get_Timeout                              */

int64_t IOTC_Session_Get_Timeout(int64_t sid)
{
    (void)sid;
    return -1; /* not implemented */
}

/* --------------------------------------------------------------------- */
/* Feature parity: IOTC_Session_Set_Timeout                              */

int64_t IOTC_Session_Set_Timeout(int64_t sid, uint32_t timeout)
{
    (void)sid; (void)timeout;
    return -1; /* not implemented */
}

/* --------------------------------------------------------------------- */
/* Feature parity: IOTC_Session_Check_Alive                              */

int64_t IOTC_Session_Check_Alive(int64_t sid)
{
    /* Return 1 if session exists, 0 otherwise */
    SessionEntry *entry = find_session(sid, 0);
    return entry ? 1 : 0;
}

/* --------------------------------------------------------------------- */
/* Feature parity: IOTC_Session_GetBufSize                               */

int64_t IOTC_Session_GetBufSize(int64_t sid)
{
    (void)sid;
    return -1; /* not implemented */
}

/* --------------------------------------------------------------------- */
/* Feature parity: IOTC_Session_Get_ConnType                             */

int64_t IOTC_Session_Get_ConnType(int64_t sid)
{
    (void)sid;
    return -1; /* not implemented */
}

/* --------------------------------------------------------------------- */
/* Feature parity: IOTC_Session_Get_Info_Ex                              */

int64_t IOTC_Session_Get_Info_Ex(int64_t sid, void *info_ex)
{
    (void)sid; (void)info_ex;
    return -1; /* not implemented */
}

/* --------------------------------------------------------------------- */
/* Feature parity: IOTC_Session_Get_Channel_ON_Bitmap                    */

uint32_t IOTC_Session_Get_Channel_ON_Bitmap(int64_t sid)
{
    SessionEntry *entry = find_session(sid, 0);
    if (!entry)
        return 0;
    return entry->chan_mask;
}